### ISSUE TITLE
Error getting some data entities

### ISSUE THREAD

**Issue by JesperLaursen** [JO-Informatik-ApS/DAWA-Replication#1]
Maybe something has changed, since You made this awesome code.
sted and vejmidte keeps failing for me.
Error message is:
ERROR! Mode Udtraek: Cannot process entity Sted. Problem: Unable to read data from the transport connection: The connection was closed..

**Comment by valdas1** [comment]
This is a known issue, and it is on our todo list.
It happens mostly when the number of items and the amount of data that the client processes is too high. This is mostly the case for entities with geometry fields.

You could try adjusting the **_UdtraekBulkSize_** value in the _DawaReplication\App.config file_ (which is 2500 by default), and set it to half of or less than the current value and see it that helps.

**Comment by JesperLaursen** [comment]
I adjusted UdtraekBulkSize to 1000, but it still didn't complete.
Then I also set DKStedBulkSize to 1000, and now it is complete without errors.
